Contact form
evans22j/My-Portfolio pull request #3
Opened 2022-02-16 09:41 UTC by evans22j

2022-02-16 10:40 UTC, Amrhub requested changes
Hi @evans22j  and @kaitcham ,  👋🏻 

Phenomenal Job! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!
These changes aim to add some awesomeness to your awesome project and code skills.

## To Highlight ✔️ 
Clean code ✔️ 
Meaningful commit messages ✔️ 
Correct workflow ✔️ 

## Required Changes ♻️
_Check the comments under the review._
![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-16 10:40 UTC, Amrhub commented on index.html
> +              maxlength="500"
- [ ] Let's make sure we have `required` on the comments textarea message as we don't want to get emails with an empty message.

2022-02-16 11:25 UTC, Hamzaoutdoors approved these changes
Hi @evans22j, 

## Congratulations! 🎉 Project Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it  🚀

To Highlight:

- [x] The Pull Request has a proper title and description. ✔️
- [x] You have added a descriptive Readme file. Good Job. ✔️
- [x] There is no linter error is present. ✔️
- [x] Project has met all the technical aspects you needed for this project! ✔️ 

_Cheers and Happy coding and Keep rocking!_ 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-17 07:48 UTC, Achilles-Dev requested changes
# Changes required :recycle:.

Please check my comments below and make all required changes.

Submit for re-review when you are done.

Thanks :smile:

2022-02-17 07:48 UTC, Achilles-Dev commented on index.html
> -          <input type="email" name="email" id="" placeholder="Email" />
Please it would be appropriate to provide a name for the input id, or better still remove it completely

2022-02-18 15:48 UTC, merged